In [34]:
# Import libraries
import numpy as np
import yfinance as yf
import plotly.express as px

In [35]:
symbol = "NQ=F"
df = yf.download(symbol, period="max", interval="1D")

df.drop(columns=["Volume"], inplace=True)
df.columns = df.columns.droplevel("Ticker")
df.dropna(inplace=True)

df.tail()

[*********************100%***********************]  1 of 1 completed

Price          Close      High       Low      Open
Date
2026-05-14  29687.75  29782.00  29448.25  29537.00
2026-05-15  29231.75  29734.00  29089.75  29690.00
2026-05-18  29096.00  29419.75  28814.75  29135.00
2026-05-19  28924.25  29188.50  28663.00  29100.00
2026-05-20  29298.00  29397.50  28797.25  28929.75

In [36]:
df["Daily_return"] = 100 * (df["Close"] - df["Open"]) / df["Open"]

df

Price          Close      High       Low      Open  Daily_return
Date
2000-09-18   3653.50   3785.50   3602.00   3721.00     -1.814028
2000-09-19   3804.00   3817.00   3656.00   3658.50      3.977040
2000-09-20   3853.00   3874.00   3715.50   3801.50      1.354728
2000-09-21   3765.00   3874.00   3744.00   3852.00     -2.258567
2000-09-22   3776.00   3780.00   3615.00   3673.00      2.804247
...              ...       ...       ...       ...           ...
2026-05-14  29687.75  29782.00  29448.25  29537.00      0.510377
2026-05-15  29231.75  29734.00  29089.75  29690.00     -1.543449
2026-05-18  29096.00  29419.75  28814.75  29135.00     -0.133860
2026-05-19  28924.25  29188.50  28663.00  29100.00     -0.603952
2026-05-20  29298.00  29397.50  28797.25  28929.75      1.272911

[6482 rows x 5 columns]

In [39]:
fig = px.bar(
    df,
    x=df.index,
    y="Daily_return",
    title="Daily returns",
    template="plotly_dark"
)

fig.show()

In [38]:
N = 5
x = 0.05

df["Cum_Daily_return"] = (
    df["Daily_return"]
    .shift(1)
    .rolling(N)
    .sum()
)

df.head(10)


# df["flag"] = df["Cum_Daily_return"] > x

# df

Price        Close    High     Low    Open  Daily_return  Cum_Daily_return
Date
2000-09-18  3653.5  3785.5  3602.0  3721.0     -1.814028               NaN
2000-09-19  3804.0  3817.0  3656.0  3658.5      3.977040               NaN
2000-09-20  3853.0  3874.0  3715.5  3801.5      1.354728               NaN
2000-09-21  3765.0  3874.0  3744.0  3852.0     -2.258567               NaN
2000-09-22  3776.0  3780.0  3615.0  3673.0      2.804247               NaN
2000-09-25  3675.0  3830.0  3660.0  3776.5     -2.687674          4.063420
2000-09-26  3611.5  3754.0  3611.5  3679.5     -1.848077          3.189775
2000-09-27  3645.0  3705.0  3580.5  3624.0      0.579470         -2.635342
2000-09-28  3758.0  3780.0  3607.0  3640.5      3.227579         -3.410601
2000-09-29  3621.0  3742.5  3608.0  3730.0     -2.922252          2.075545