In [22]:
import sys
import os

sys.path.append(os.path.abspath(".."))

from utils import describe_data, plot_df_chart

In [23]:
# Import libraries
import numpy as np
import yfinance as yf
import plotly.express as px

In [24]:
symbol = "NQ=F"
df = yf.download(symbol, period="max", interval="1D")

df.drop(columns=["Volume"], inplace=True)
df.columns = df.columns.droplevel("Ticker")
df.dropna(inplace=True)

df.tail()

[*********************100%***********************]  1 of 1 completed

Price          Close      High       Low      Open
Date
2026-05-15  29231.75  29734.00  29089.75  29690.00
2026-05-18  29096.00  29419.75  28814.75  29135.00
2026-05-19  28924.25  29188.50  28663.00  29100.00
2026-05-20  29390.50  29397.50  28797.25  28929.75
2026-05-21  29364.75  29554.00  29113.00  29253.00

In [25]:
df["Daily_return"] = 100 * (df["Close"] - df["Open"]) / df["Open"]

df.tail()

Price          Close      High       Low      Open  Daily_return
Date
2026-05-15  29231.75  29734.00  29089.75  29690.00     -1.543449
2026-05-18  29096.00  29419.75  28814.75  29135.00     -0.133860
2026-05-19  28924.25  29188.50  28663.00  29100.00     -0.603952
2026-05-20  29390.50  29397.50  28797.25  28929.75      1.592651
2026-05-21  29364.75  29554.00  29113.00  29253.00      0.382012

In [26]:
N = 5

df["Cum_Daily_return"] = (
    df["Daily_return"]
    .shift(1)
    .rolling(N)
    .sum()
)

df.dropna(inplace=True)

df.head(10)

Price        Close    High     Low    Open  Daily_return  Cum_Daily_return
Date
2000-09-25  3675.0  3830.0  3660.0  3776.5     -2.687674          4.063420
2000-09-26  3611.5  3754.0  3611.5  3679.5     -1.848077          3.189775
2000-09-27  3645.0  3705.0  3580.5  3624.0      0.579470         -2.635342
2000-09-28  3758.0  3780.0  3607.0  3640.5      3.227579         -3.410601
2000-09-29  3621.0  3742.5  3608.0  3730.0     -2.922252          2.075545
2000-10-02  3528.5  3668.0  3492.0  3621.0     -2.554543         -3.650954
2000-10-03  3397.0  3603.0  3385.0  3529.0     -3.740436         -3.517823
2000-10-04  3477.5  3477.5  3334.0  3426.5      1.488399         -5.410183
2000-10-05  3482.5  3537.0  3431.5  3460.5      0.635746         -4.501253
2000-10-06  3357.5  3509.5  3305.0  3490.0     -3.796562         -7.093086

In [27]:
plot_df_chart(
    df["Cum_Daily_return"],
    chart_type="bar",
    chart_title="Cumulative Daily returns",
    yaxis_title="Cumulative Daily Return (%)",
    width=1000,
    height=600,
)

## Stats

In [28]:
df_stats, stats = describe_data(df["Cum_Daily_return"])

df_stats

              Value
Metric
nobs           6478
Min %     -22.90379
Max %     17.475658
Mean %     0.206126
Median %   0.456297
Mode %    -22.90379
Variance  10.898603
Skewness  -0.513262
Kurtosis   3.909717

In [30]:
x = 5

conditions = [
    df["Cum_Daily_return"] < -x,
    df["Cum_Daily_return"] > x
]

choices = ["bear", "bull"]

df["flag"] = np.select(conditions, choices, default="sideways")

df.head(20)

Price,Close,High,Low,Open,Daily_return,Cum_Daily_return,flag
Date,,,,,,,
2000-09-25,3675.0,3830.0,3660.0,3776.5,-2.687674,4.063420,sideways
2000-09-26,3611.5,3754.0,3611.5,3679.5,-1.848077,3.189775,sideways
2000-09-27,3645.0,3705.0,3580.5,3624.0,0.579470,-2.635342,sideways
2000-09-28,3758.0,3780.0,3607.0,3640.5,3.227579,-3.410601,sideways
2000-09-29,3621.0,3742.5,3608.0,3730.0,-2.922252,2.075545,sideways
2000-10-02,3528.5,3668.0,3492.0,3621.0,-2.554543,-3.650954,sideways
2000-10-03,3397.0,3603.0,3385.0,3529.0,-3.740436,-3.517823,sideways
2000-10-04,3477.5,3477.5,3334.0,3426.5,1.488399,-5.410183,bear
2000-10-05,3482.5,3537.0,3431.5,3460.5,0.635746,-4.501253,sideways
2000-10-06,3357.5,3509.5,3305.0,3490.0,-3.796562,-7.093086,bear
2000-10-09,3349.5,3402.0,3222.0,3359.5,-0.297663,-7.967395,bear
2000-10-10,3160.0,3381.0,3155.0,3346.5,-5.572987,-5.710516,bear
2000-10-11,3124.5,3258.0,3070.5,3191.5,-2.099326,-7.543066,bear
2000-10-12,3046.5,3224.0,3024.0,3145.0,-3.131955,-11.130792,bear
2000-10-13,3270.5,3309.0,3021.5,3060.5,6.861624,-14.898493,bear
2000-10-16,3316.0,3334.0,3237.5,3274.0,1.282834,-4.240308,sideways
2000-10-17,3170.0,3369.0,3160.5,3308.0,-4.171705,-2.659810,sideways
2000-10-18,3155.0,3296.0,3025.0,3202.5,-1.483216,-1.258528,sideways
2000-10-19,3447.0,3447.0,3180.0,3180.0,8.396226,-0.642418,sideways
2000-10-20,3499.5,3555.5,3412.0,3437.0,1.818446,10.885764,bull