In [1]:
import pandas as pd
import numpy as np
from utils import get_data, prep_data, bb_scalp, backtest_stats

In [2]:
BB_WINDOW = 73
ATR_WINDOW = 5
BB_ZSCORE = 3
ATR_MULT = 1
RRR = 1

BB_UPPER = "bb_upper"
BB_LOWER = "bb_lower"
BB_MIDDLE = "bb_middle"
ATR = "ATR"

In [3]:
df = get_data('../data/XAUUSD_M5_01-01-2025_to_24-08-2026.csv')

df

                        Open     High      Low    Close
Datetime
2025-03-26 04:20:00  3018.88  3019.02  3017.69  3018.34
2025-03-26 04:25:00  3018.34  3019.64  3018.34  3018.63
2025-03-26 04:30:00  3018.59  3020.46  3018.28  3020.01
2025-03-26 04:35:00  3020.01  3021.13  3019.80  3020.34
2025-03-26 04:40:00  3020.34  3022.86  3020.05  3022.86
...                      ...      ...      ...      ...
2026-08-24 14:30:00  4646.61  4652.14  4643.51  4652.14
2026-08-24 14:35:00  4651.97  4670.01  4650.81  4660.51
2026-08-24 14:40:00  4660.52  4666.49  4654.22  4658.73
2026-08-24 14:45:00  4658.93  4661.58  4648.34  4649.02
2026-08-24 14:50:00  4649.04  4659.63  4648.46  4659.63

[100167 rows x 4 columns]

In [4]:
_df = prep_data(df.copy(), atr_window=ATR_WINDOW, bb_window=BB_WINDOW, bb_zscore=BB_ZSCORE)

In [5]:
_df

,Open,High,Low,Close,ATR,bb_middle,bb_upper,bb_lower,Signal
Datetime,,,,,,,,,
2025-03-26 10:20:00,3026.30,3026.70,3025.19,3025.74,1.192,3021.127961,3033.206609,3009.049312,0
2025-03-26 10:25:00,3025.74,3027.00,3025.45,3026.42,1.360,3021.270989,3033.461466,3009.080511,0
2025-03-26 10:30:00,3026.41,3028.34,3026.34,3028.10,1.366,3021.455556,3033.858621,3009.052492,0
2025-03-26 10:35:00,3028.10,3028.74,3027.10,3027.66,1.442,3021.623244,3034.222217,3009.024271,0
2025-03-26 10:40:00,3027.66,3029.20,3027.66,3029.03,1.576,3021.823427,3034.703705,3008.943148,0
...,...,...,...,...,...,...,...,...,...
2026-08-24 14:30:00,4646.61,4652.14,4643.51,4652.14,5.628,4641.789104,4658.837142,4624.741065,0
2026-08-24 14:35:00,4651.97,4670.01,4650.81,4660.51,6.012,4642.295074,4660.050361,4624.539787,-1
2026-08-24 14:40:00,4660.52,4666.49,4654.22,4658.73,8.726,4642.739261,4660.948265,4624.530257,0
2026-08-24 14:45:00,4658.93,4661.58,4648.34,4649.02,10.416,4642.909011,4660.870510,4624.947511,0
2026-08-24 14:50:00,4649.04,4659.63,4648.46,4659.63,12.014,4643.360929,4662.071170,4624.650689,0

In [6]:
result_df = bb_scalp(_df, rrr=RRR, atr_mult=ATR_MULT, max_lookahead=60)


result_df

                     PnL  Cumulative_PnL  Balance
Datetime
2025-03-26 10:20:00  0.0             0.0   1000.0
2025-03-26 10:25:00  0.0             0.0   1000.0
2025-03-26 10:30:00  0.0             0.0   1000.0
2025-03-26 10:35:00  0.0             0.0   1000.0
2025-03-26 10:40:00  0.0             0.0   1000.0
...                  ...             ...      ...
2026-08-24 14:30:00  0.0           -69.0    310.0
2026-08-24 14:35:00 -1.0           -70.0    300.0
2026-08-24 14:40:00  0.0           -70.0    300.0
2026-08-24 14:45:00  0.0           -70.0    300.0
2026-08-24 14:50:00  0.0           -70.0    300.0

[100095 rows x 3 columns]

In [7]:
backtest_stats(result_df, 1000)

{'Return %': np.float64(-70.0),
 'Sharp ratio': np.float64(-346.91),
 'Max Balance DD': np.float64(830.0),
 'Max Balance DD %': np.float64(80.58),
 'Win rate': np.float64(47.19),
 'Winning trades': 588,
 'Losing trades': 658,
 'N° trades': 1246,
 'Max win streak': 9,
 'Max loss streak': 12}