In [1]:
import pandas as pd

In [19]:
df = pd.read_csv('XAUUSD_M5_2025.csv')

df["Datetime"] = pd.to_datetime(
    df["DATE"].astype(str) + " " + df["TIME"].astype(str)
)

# df.set_index("Datetime", inplace=True)

df = df[["Datetime", "Open", "High", "Low", "Close"]]

df

                  Datetime     Open     High      Low    Close
0      2025-03-26 04:20:00  3018.88  3019.02  3017.69  3018.34
1      2025-03-26 04:25:00  3018.34  3019.64  3018.34  3018.63
2      2025-03-26 04:30:00  3018.59  3020.46  3018.28  3020.01
3      2025-03-26 04:35:00  3020.01  3021.13  3019.80  3020.34
4      2025-03-26 04:40:00  3020.34  3022.86  3020.05  3022.86
...                    ...      ...      ...      ...      ...
100162 2026-08-24 14:30:00  4646.61  4652.14  4643.51  4652.14
100163 2026-08-24 14:35:00  4651.97  4670.01  4650.81  4660.51
100164 2026-08-24 14:40:00  4660.52  4666.49  4654.22  4658.73
100165 2026-08-24 14:45:00  4658.93  4661.58  4648.34  4649.02
100166 2026-08-24 14:50:00  4649.04  4659.63  4648.46  4659.63

[100167 rows x 5 columns]

# Cleaness

In [22]:
# Chronological order
print("Sorted:", df["Datetime"].is_monotonic_increasing)

Sorted: True

In [20]:
# Basic structure
print("Rows:", len(df))
print("Missing values:")
print(df.isna().sum())

Rows: 100167
Missing values:
Datetime    0
Open        0
High        0
Low         0
Close       0
dtype: int64

In [21]:
# Duplicate Datetimes
print("Duplicate Datetimes:", df["Datetime"].duplicated().sum())

# df[df.duplicated(keep=False)]

Duplicate Datetimes: 0

In [24]:
# OHLC validity
bad_ohlc = (
    (df["High"] < df[["Open", "Close"]].max(axis=1)) |
    (df["Low"] > df[["Open", "Close"]].min(axis=1)) |
    (df["High"] < df["Low"]) |
    (df[["Open", "High", "Low", "Close"]] <= 0).any(axis=1)
)

print("Bad OHLC rows:", bad_ohlc.sum())

Bad OHLC rows: 0

In [25]:
# Show problematic rows
df[bad_ohlc].head(20)

Empty DataFrame
Columns: [Datetime, Open, High, Low, Close]
Index: []