In [2]:
import pandas as pd
import numpy as np
from itertools import product
from pathlib import Path
from collections import defaultdict

from utils import get_data, backtest_stats, run_range_breakout, get_time_to_roots, compute_range

### Data

In [3]:
df = get_data("../data/XAUUSD_M5_01-01-2025_to_24-08-2026.csv")

df = df.tail(10000)

df

                        Open     High      Low    Close
Datetime
2026-07-03 05:35:00  4180.86  4186.85  4179.42  4186.31
2026-07-03 05:40:00  4186.32  4186.92  4181.49  4183.33
2026-07-03 05:45:00  4183.33  4184.28  4178.94  4180.29
2026-07-03 05:50:00  4180.29  4186.08  4179.28  4183.72
2026-07-03 05:55:00  4183.72  4186.68  4182.59  4183.63
...                      ...      ...      ...      ...
2026-08-24 14:30:00  4646.61  4652.14  4643.51  4652.14
2026-08-24 14:35:00  4651.97  4670.01  4650.81  4660.51
2026-08-24 14:40:00  4660.52  4666.49  4654.22  4658.73
2026-08-24 14:45:00  4658.93  4661.58  4648.34  4649.02
2026-08-24 14:50:00  4649.04  4659.63  4648.46  4659.63

[10000 rows x 4 columns]

In [5]:
time_to_roots = get_time_to_roots(df)

In [9]:
result = run_range_breakout(
    df,
    root_indices=time_to_roots["09:30"],
    range_length=3,
    rrr=2,
    max_lookahead=None,
)

result

                     PnL  Cumulative_PnL  Balance
Datetime
2026-07-03 05:35:00  0.0             0.0   1000.0
2026-07-03 05:40:00  0.0             0.0   1000.0
2026-07-03 05:45:00  0.0             0.0   1000.0
2026-07-03 05:50:00  0.0             0.0   1000.0
2026-07-03 05:55:00  0.0             0.0   1000.0
...                  ...             ...      ...
2026-08-24 14:30:00  0.0            -1.0    990.0
2026-08-24 14:35:00  0.0            -1.0    990.0
2026-08-24 14:40:00  0.0            -1.0    990.0
2026-08-24 14:45:00  0.0            -1.0    990.0
2026-08-24 14:50:00  0.0            -1.0    990.0

[10000 rows x 3 columns]

In [10]:
backtest_stats(result)

{'Return %': np.float64(-1.0),
 'Sharp ratio': np.float64(-11.57),
 'Max Balance DD': np.float64(70.0),
 'Max Balance DD %': np.float64(6.8),
 'Win rate': np.float64(32.43),
 'Winning trades': 12,
 'Losing trades': 25,
 'N° trades': 37,
 'Max win streak': 3,
 'Max loss streak': 4}

### functions